"""Agent 8 — Reporting Agent.

Produces the executive-friendly investigation report described in the
brief's demonstration scenario (section 14): Executive Summary, Risk
Score, Detected Anomalies, Supporting Evidence, Financial Impact,
Recommended Actions, Investigation Priority.

Narrative text here is generated by a deterministic, rule-based
NarrativeGenerator so the report is reproducible and testable without any
external AI call. In production this is the natural seam for an Azure
OpenAI-backed generator that phrases the same structured findings more
fluently — the report *structure* and every number in it come from the
deterministic agents upstream either way, so swapping the narrative layer
can never change a risk score or a finding.
"""

from __future__ import annotations

from innoligo.agents.invoice_intelligence import InvoiceSignals
from innoligo.agents.investigation import InvestigationPlan
from innoligo.models import Invoice, RiskAssessment, Severity

_SEVERITY_LABEL = {
    Severity.CRITICAL: "Critical",
    Severity.HIGH: "High",
    Severity.MEDIUM: "Medium",
    Severity.LOW: "Low",
    Severity.INFO: "Info",
}


def _count_by_severity(assessment: RiskAssessment) -> dict[str, int]:
    counts = {label: 0 for label in _SEVERITY_LABEL.values()}
    for finding in assessment.findings:
        counts[_SEVERITY_LABEL[finding.severity]] += 1
    return counts


def estimate_financial_impact(invoice: Invoice, signals: InvoiceSignals) -> dict:
    """Deterministically estimate the currency amount placed at risk by
    the findings, so the report can quote a concrete financial impact
    rather than only a qualitative risk level.
    """
    at_risk = 0.0
    notes: list[str] = []

    if not signals.math["total_ok"]:
        amt = abs(signals.math["total_diff"])
        at_risk += amt
        notes.append(f"{invoice.currency} {amt:.2f} discrepancy between stated and recalculated invoice total")

    if signals.po_comparison and signals.po_comparison["exceeds_tolerance"]:
        amt = abs(signals.po_comparison["invoice_subtotal"] - signals.po_comparison["po_approved_total"])
        at_risk += amt
        notes.append(f"{invoice.currency} {amt:.2f} above the approved purchase order total")

    if signals.bank_details and signals.bank_details["bank_details_changed"]:
        at_risk += invoice.total
        notes.append(
            f"{invoice.currency} {invoice.total:.2f} full invoice value at risk of payment redirection "
            f"to unverified bank details"
        )

    if signals.duplicates["duplicate_invoice_number"] or signals.duplicates["same_amount_same_supplier"]:
        at_risk += invoice.total
        notes.append(f"{invoice.currency} {invoice.total:.2f} potential duplicate payment exposure")

    return {"currency": invoice.currency, "estimated_amount_at_risk": round(at_risk, 2), "notes": notes}


def build_report(
    invoice: Invoice,
    assessment: RiskAssessment,
    plan: InvestigationPlan,
    signals: InvoiceSignals,
    *,
    company_name: str = "Innoligo Demo Client Ltd",
) -> str:
    counts = _count_by_severity(assessment)
    impact = estimate_financial_impact(invoice, signals)

    lines: list[str] = []
    lines.append(f"# AI Financial Risk & Fraud Investigation Report")
    lines.append("")
    lines.append(f"**Subject:** Invoice {invoice.invoice_number} — {invoice.supplier_name}")
    lines.append(f"**Prepared for:** {company_name}")
    lines.append(f"**Classification:** AI-assisted decision support — not a determination of fraud")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append("")
    if assessment.findings:
        lines.append(
            f"The AI Invoice Fraud & Financial Document Checker reviewed invoice "
            f"{invoice.invoice_number} from {invoice.supplier_name} ({invoice.currency} "
            f"{invoice.total:.2f}) against its purchase order, supplier master record and "
            f"payment record, and identified {len(assessment.findings)} risk indicator(s) "
            f"requiring human review. This is a decision-support output, not a finding of fraud."
        )
    else:
        lines.append(
            f"The AI Invoice Fraud & Financial Document Checker reviewed invoice "
            f"{invoice.invoice_number} from {invoice.supplier_name} and found no risk "
            f"indicators against the documents supplied."
        )
    lines.append("")

    lines.append("## Risk Score")
    lines.append("")
    lines.append(f"**Financial Risk Score: {assessment.score}/100 — {assessment.level.value.upper()}**")
    lines.append("")
    lines.append(
        f"{counts['Critical']} Critical, {counts['High']} High, {counts['Medium']} Medium, "
        f"{counts['Low']} Low finding(s)."
    )
    lines.append("")

    lines.append("## Detected Anomalies & Supporting Evidence")
    lines.append("")
    if assessment.findings:
        for i, finding in enumerate(assessment.findings, start=1):
            lines.append(f"### {i}. [{_SEVERITY_LABEL[finding.severity]}] {finding.title}")
            lines.append(f"- **What happened:** {finding.what_happened}")
            lines.append(f"- **Why it's suspicious:** {finding.why_suspicious}")
            lines.append(f"- **Supporting evidence:** {', '.join(finding.evidence)}")
            lines.append(f"- **Recommended action:** {finding.recommended_action}")
            lines.append("")
    else:
        lines.append("No anomalies detected.")
        lines.append("")

    lines.append("## Financial Impact")
    lines.append("")
    lines.append(f"**Estimated amount at risk: {impact['currency']} {impact['estimated_amount_at_risk']:.2f}**")
    lines.append("")
    for note in impact["notes"]:
        lines.append(f"- {note}")
    if not impact["notes"]:
        lines.append("- No quantifiable financial exposure identified.")
    lines.append("")

    lines.append("## Recommended Actions")
    lines.append("")
    lines.append(f"**Hold payment:** {'Yes' if plan.hold_payment else 'No'}")
    lines.append("")
    for step in plan.next_steps or ["No further action required."]:
        lines.append(f"- {step}")
    lines.append("")

    lines.append("## Additional Evidence Requested")
    lines.append("")
    for item in plan.additional_evidence_requested:
        lines.append(f"- {item}")
    lines.append("")

    lines.append("## Investigation Priority")
    lines.append("")
    lines.append(plan.priority)
    lines.append("")

    lines.append("---")
    lines.append(
        "*This report is generated by an AI decision-support system. It identifies "
        "potential anomalies and suspicious indicators for human review. It does not "
        "constitute a legal, regulatory or definitive determination that any person or "
        "organisation has committed fraud. Final decisions rest with authorised human "
        "investigators and compliance teams.*"
    )

    return "\n".join(lines)
